# Generated by Django 2.2.4 on 2019-12-05 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ostan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ostan', models.CharField(max_length=20, verbose_name='استان')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_code', models.CharField(max_length=40, verbose_name='کد منطقه')),
                ('u_name', models.CharField(max_length=50, verbose_name='نام منطقه')),
            ],
        ),
        migrations.CreateModel(
            name='Rosta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rosta', models.CharField(max_length=50, verbose_name='روستا')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.City')),
            ],
        ),
        migrations.CreateModel(
            name='Melk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('melk_name', models.CharField(max_length=100, verbose_name='نام ملک')),
                ('khayer_name', models.CharField(max_length=100, verbose_name='نام واگذارکننده')),
                ('sanad_asli', models.CharField(max_length=20, verbose_name='شماره سند اصلی')),
                ('sanad_farye', models.CharField(max_length=20, verbose_name='شماره سند فرعی')),
                ('sanad_type', models.CharField(max_length=50, verbose_name='نوع سند واگذاری')),
                ('melk_state', models.CharField(max_length=50, verbose_name='وضعیت کنونی ملک')),
                ('melk_motavali', models.CharField(max_length=100, verbose_name='متولی ملک')),
                ('melk_karbari', models.CharField(max_length=50, verbose_name='نوع کاربری ملک')),
                ('melk_year', models.DateField(verbose_name='سال واگذاری ملک')),
                ('melk_arseh', models.CharField(max_length=20, verbose_name='عرصه ملک')),
                ('melk_price', models.CharField(max_length=50, verbose_name='ارزش ریالی ملک')),
                ('melk_ayan', models.CharField(max_length=20, verbose_name='اعیان ملک')),
                ('melk_comment', models.CharField(max_length=1000, verbose_name='توضیحات سند ملک')),
                ('melk_pic', models.CharField(max_length=100, verbose_name='تصویر سند ملک')),
                ('post_code', models.CharField(max_length=10, verbose_name='کدپستی')),
                ('address', models.CharField(max_length=200, verbose_name='آدرس ملک')),
                ('melk_gps', models.CharField(max_length=100, verbose_name='موقعیت جغرافیایی ملک')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.City', verbose_name='شهرستان')),
                ('ostan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ostan', verbose_name='استان')),
               
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='ostan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ostan', verbose_name='شهرستان'),
        ),
    ]
