# Generated by Django 2.2.4 on 2019-12-15 16:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191206_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.AlterField(
            model_name='melk',
            name='melk_karbari',
            field=models.CharField(choices=[('آموزشی', 'آموزشی'), ('اداری', 'اداری'), ('مسکونی', 'مسکونی'), ('غیره', 'غیره')], max_length=50, verbose_name='نوع کاربری ملک'),
        ),
        migrations.AlterField(
            model_name='melk',
            name='melk_motavali',
            field=models.CharField(choices=[('آموزش و پرورش', ' آموزش و پرورش'), ('اوقاف', 'اوقاف'), ('دولت', 'دولت'), ('آستانه', 'آستانه'), ('غیره', 'غیره')], max_length=100, verbose_name='متولی ملک'),
        ),
        migrations.AlterField(
            model_name='melk',
            name='melk_state',
            field=models.CharField(choices=[('در حال بهره برداری', 'درحال بهره برداری'), ('کشاورزی', 'کشاورزی'), ('زمین', 'زمین')], max_length=50, verbose_name='وضعیت کنونی ملک'),
        ),
    ]
