# Generated by Django 2.2.4 on 2019-12-17 17:59

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191217_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='melk',
            name='melk_year',
            field=django_jalali.db.models.jDateField(verbose_name='سال واگذاری ملک'),
        ),
    ]
