# Generated by Django 2.2.4 on 2020-02-08 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191223_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='ostan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Ostan', verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='melk',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.City', verbose_name='شهرستان'),
        ),
        migrations.AlterField(
            model_name='melk',
            name='melk_arseh',
            field=models.CharField(max_length=10, verbose_name='عرصه ملک'),
        ),
        migrations.AlterField(
            model_name='melk',
            name='melk_ayan',
            field=models.CharField(max_length=10, verbose_name='اعیان ملک'),
        ),
        migrations.AlterField(
            model_name='melk',
            name='melk_price',
            field=models.CharField(max_length=20, verbose_name='ارزش ریالی ملک'),
        ),
        migrations.AlterField(
            model_name='melk',
            name='melk_year',
            field=models.DateField(verbose_name='سال واگذاری ملک'),
        ),
        migrations.AlterField(
            model_name='melk',
            name='ostan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Ostan', verbose_name='استان'),
        ),
       
       
    ]
