# Generated by Django 2.2.4 on 2020-02-23 07:25

import django.contrib.gis.geos.point
from django.db import migrations, models
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200209_0026'),
    ]

    operations = [
        
       
        migrations.AlterField(
            model_name='melk',
            name='melk_gps',
            field=location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(59.0, 36.0), srid=4326, verbose_name='موقعیت جغرافیایی ملک'),
        ),
       
    ]
